import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, SalesDocumentStatus } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { CreateInvoicePaymentDto, CreateSalesDocumentDto, SalesDocumentQueryDto, UpdateSalesDocumentDto } from "./dto/sales-document.dto";
import { calculateDocumentTotals, ensureCustomer, ensureProducts, generateDocumentNumber, mapDocumentItems, withDocumentNumber, withDocumentNumbers } from "./sales-documents.util";

type SalesDocumentLine = { productId?: string | null; customName?: string | null; customType?: string | null; customNote?: string | null; quantity: number; unitPrice: Prisma.Decimal; discount: Prisma.Decimal; tax: Prisma.Decimal; total: Prisma.Decimal };

@Injectable()
export class ProformasService { constructor(private readonly prisma: PrismaService) {}
  async findAll(tenantId:string,query:SalesDocumentQueryDto){const page=query.page??1;const limit=query.limit??20;const where:Prisma.ProformaWhereInput={tenantId,status:query.status as SalesDocumentStatus,OR:query.search?[{documentNumber:{contains:query.search,mode:"insensitive"}},{customer:{displayName:{contains:query.search,mode:"insensitive"}}}]:undefined};const[items,total]=await this.prisma.$transaction([this.prisma.proforma.findMany({where,include:{customer:true,quote:true,items:{include:{product:true}},payments:true},skip:(page-1)*limit,take:limit,orderBy:{createdAt:"desc"}}),this.prisma.proforma.count({where})]);return{items:withDocumentNumbers(items),meta:{page,limit,total,pageCount:Math.ceil(total/limit)}};}
  async findOne(tenantId:string,id:string){const proforma=await this.prisma.proforma.findFirst({where:{id,tenantId},include:{customer:true,quote:true,items:{include:{product:true}},invoices:true,payments:true}});if(!proforma)throw new NotFoundException("Commande introuvable");return withDocumentNumber({...proforma,customerHistoryPrepared:true,stockUpdatePrepared:false,printFormats:["POS_58_80","A4_LETTER"]});}
  async create(tenantId:string,dto:CreateSalesDocumentDto,createdById?:string){await ensureCustomer(this.prisma,tenantId,dto.customerId);await ensureProducts(this.prisma,tenantId,dto.items.map(i=>i.productId).filter((productId): productId is string => Boolean(productId)));const totals=calculateDocumentTotals(dto.items,dto.discount??0);return withDocumentNumber(await this.prisma.proforma.create({data:{tenantId,customerId:dto.customerId,documentNumber:generateDocumentNumber("CMD"),status:SalesDocumentStatus.CONFIRMED,notes:dto.notes,createdById,...totals,items:{create:mapDocumentItems(dto.items)}},include:{customer:true,items:{include:{product:true}},payments:true}}));}
  async update(tenantId:string,id:string,dto:UpdateSalesDocumentDto){const proforma=await this.findOne(tenantId,id);if(!([SalesDocumentStatus.DRAFT,SalesDocumentStatus.SENT,SalesDocumentStatus.CONFIRMED] as SalesDocumentStatus[]).includes(proforma.status))throw new BadRequestException("Cette commande ne peut plus etre modifiee");await ensureCustomer(this.prisma,tenantId,dto.customerId);await ensureProducts(this.prisma,tenantId,dto.items.map(i=>i.productId).filter((productId): productId is string => Boolean(productId)));const totals=calculateDocumentTotals(dto.items,dto.discount??0);return withDocumentNumber(await this.prisma.proforma.update({where:{id},data:{customerId:dto.customerId,notes:dto.notes,...totals,items:{deleteMany:{},create:mapDocumentItems(dto.items)}},include:{customer:true,items:{include:{product:true}},payments:true}}));}
  async convertToInvoice(tenantId:string,id:string,createdById?:string){const proforma=await this.findOne(tenantId,id);if(([SalesDocumentStatus.CANCELLED,SalesDocumentStatus.CONVERTED] as SalesDocumentStatus[]).includes(proforma.status))throw new BadRequestException("Cette proforma ne peut pas etre transformee");const lines=proforma.items as SalesDocumentLine[];const invoice=await this.prisma.invoice.create({data:{tenantId,customerId:proforma.customerId,proformaId:proforma.id,documentNumber:generateDocumentNumber("INV"),status:SalesDocumentStatus.SENT,subtotal:proforma.subtotal,discount:proforma.discount,tax:proforma.tax,total:proforma.total,paidAmount:proforma.paidAmount,balance:proforma.balance,notes:proforma.notes,createdById,issuedAt:new Date(),items:{create:lines.map((item)=>({productId:item.productId,customName:item.customName,customType:item.customType,customNote:item.customNote,quantity:item.quantity,unitPrice:item.unitPrice,discount:item.discount,tax:item.tax,total:item.total}))}},include:{customer:true,items:{include:{product:true}}}});await this.prisma.proforma.update({where:{id},data:{status:SalesDocumentStatus.CONVERTED}});return withDocumentNumber(invoice);}
  async updateStatus(tenantId:string,id:string,status:SalesDocumentStatus){const allowed:SalesDocumentStatus[]=[SalesDocumentStatus.CONFIRMED,SalesDocumentStatus.IN_PROGRESS,SalesDocumentStatus.READY,SalesDocumentStatus.DELIVERED,SalesDocumentStatus.COMPLETED,SalesDocumentStatus.CANCELLED];if(!allowed.includes(status))throw new BadRequestException("Statut de commande invalide");await this.findOne(tenantId,id);return withDocumentNumber(await this.prisma.proforma.update({where:{id},data:{status},include:{customer:true,items:{include:{product:true}},payments:true}}));}
  async registerPayment(tenantId:string,id:string,dto:CreateInvoicePaymentDto){const proforma=await this.findOne(tenantId,id);if(proforma.status===SalesDocumentStatus.CANCELLED)throw new BadRequestException("Commande annulée");if(Number(proforma.balance)<=0)throw new BadRequestException("Commande déjà soldée");if(dto.amount>Number(proforma.balance))throw new BadRequestException("Paiement supérieur au solde");const paidAmount=Number(proforma.paidAmount)+dto.amount;const balance=Number(proforma.total)-paidAmount;const status=balance<=0?SalesDocumentStatus.PAID:SalesDocumentStatus.PARTIALLY_PAID;await this.prisma.payment.create({data:{proformaId:id,method:dto.method,amount:dto.amount,reference:dto.reference,notes:dto.notes}});return withDocumentNumber(await this.prisma.proforma.update({where:{id},data:{paidAmount,balance,status},include:{customer:true,items:{include:{product:true}},payments:true}}));}
  async summary(tenantId:string){const active=[SalesDocumentStatus.CONFIRMED,SalesDocumentStatus.IN_PROGRESS,SalesDocumentStatus.READY,SalesDocumentStatus.PARTIALLY_PAID];const [inProgress,readyUnpaid,completed,payments,balances]=await this.prisma.$transaction([this.prisma.proforma.count({where:{tenantId,status:{in:active}}}),this.prisma.proforma.count({where:{tenantId,status:SalesDocumentStatus.READY,balance:{gt:0}}}),this.prisma.proforma.count({where:{tenantId,status:{in:[SalesDocumentStatus.COMPLETED,SalesDocumentStatus.PAID]}}}),this.prisma.payment.aggregate({where:{proforma:{tenantId}},_sum:{amount:true}}),this.prisma.proforma.aggregate({where:{tenantId,status:{notIn:[SalesDocumentStatus.CANCELLED,SalesDocumentStatus.CONVERTED]}},_sum:{balance:true}})]);return{ordersInProgress:inProgress,depositsReceived:Number(payments._sum.amount??0),balancesToCollect:Number(balances._sum.balance??0),readyUnpaidOrders:readyUnpaid,completedOrders:completed};}
}
