import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, SalesDocumentStatus } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { CreateSalesDocumentDto, SalesDocumentQueryDto, UpdateSalesDocumentDto } from "./dto/sales-document.dto";
import { calculateDocumentTotals, ensureCustomer, ensureProducts, generateDocumentNumber, mapDocumentItems, withDocumentNumber, withDocumentNumbers } from "./sales-documents.util";

@Injectable()
export class ProformasService { constructor(private readonly prisma: PrismaService) {}
  async findAll(tenantId:string,query:SalesDocumentQueryDto){const page=query.page??1;const limit=query.limit??20;const where:Prisma.ProformaWhereInput={tenantId,status:query.status as SalesDocumentStatus,OR:query.search?[{documentNumber:{contains:query.search,mode:"insensitive"}},{customer:{displayName:{contains:query.search,mode:"insensitive"}}}]:undefined};const[items,total]=await this.prisma.$transaction([this.prisma.proforma.findMany({where,include:{customer:true,quote:true,items:{include:{product:true}}},skip:(page-1)*limit,take:limit,orderBy:{createdAt:"desc"}}),this.prisma.proforma.count({where})]);return{items:withDocumentNumbers(items),meta:{page,limit,total,pageCount:Math.ceil(total/limit)}};}
  async findOne(tenantId:string,id:string){const proforma=await this.prisma.proforma.findFirst({where:{id,tenantId},include:{customer:true,quote:true,items:{include:{product:true}},invoices:true}});if(!proforma)throw new NotFoundException("Proforma introuvable");return withDocumentNumber({...proforma,customerHistoryPrepared:true,printFormats:["POS_58_80","A4_LETTER"]});}
  async create(tenantId:string,dto:CreateSalesDocumentDto,createdById?:string){await ensureCustomer(this.prisma,tenantId,dto.customerId);await ensureProducts(this.prisma,tenantId,dto.items.map(i=>i.productId));const totals=calculateDocumentTotals(dto.items,dto.discount??0);return withDocumentNumber(await this.prisma.proforma.create({data:{tenantId,customerId:dto.customerId,documentNumber:generateDocumentNumber("PF"),notes:dto.notes,createdById,...totals,items:{create:mapDocumentItems(dto.items)}},include:{customer:true,items:{include:{product:true}}}}));}
  async update(tenantId:string,id:string,dto:UpdateSalesDocumentDto){const proforma=await this.findOne(tenantId,id);if(!([SalesDocumentStatus.DRAFT,SalesDocumentStatus.SENT] as SalesDocumentStatus[]).includes(proforma.status))throw new BadRequestException("Cette proforma ne peut plus etre modifiee");await ensureCustomer(this.prisma,tenantId,dto.customerId);await ensureProducts(this.prisma,tenantId,dto.items.map(i=>i.productId));const totals=calculateDocumentTotals(dto.items,dto.discount??0);return withDocumentNumber(await this.prisma.proforma.update({where:{id},data:{customerId:dto.customerId,notes:dto.notes,...totals,items:{deleteMany:{},create:mapDocumentItems(dto.items)}},include:{customer:true,items:{include:{product:true}}}}));}
  async convertToInvoice(tenantId:string,id:string,createdById?:string){const proforma=await this.findOne(tenantId,id);if(([SalesDocumentStatus.CANCELLED,SalesDocumentStatus.CONVERTED] as SalesDocumentStatus[]).includes(proforma.status))throw new BadRequestException("Cette proforma ne peut pas etre transformee");const invoice=await this.prisma.invoice.create({data:{tenantId,customerId:proforma.customerId,proformaId:proforma.id,documentNumber:generateDocumentNumber("INV"),status:SalesDocumentStatus.SENT,subtotal:proforma.subtotal,discount:proforma.discount,tax:proforma.tax,total:proforma.total,paidAmount:0,balance:proforma.balance,notes:proforma.notes,createdById,issuedAt:new Date(),items:{create:proforma.items.map((item:any)=>({productId:item.productId,quantity:item.quantity,unitPrice:item.unitPrice,discount:item.discount,tax:item.tax,total:item.total}))}},include:{customer:true,items:{include:{product:true}}}});await this.prisma.proforma.update({where:{id},data:{status:SalesDocumentStatus.CONVERTED}});return withDocumentNumber(invoice);}
}