import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, SalesDocumentStatus } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { CreateSalesDocumentDto, SalesDocumentQueryDto, UpdateSalesDocumentDto } from "./dto/sales-document.dto";
import { calculateDocumentTotals, ensureCustomer, ensureProducts, generateDocumentNumber, mapDocumentItems, withDocumentNumber, withDocumentNumbers } from "./sales-documents.util";

@Injectable()
export class QuotesService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll(tenantId: string, query: SalesDocumentQueryDto) { const page=query.page??1; const limit=query.limit??20; const where:Prisma.QuoteWhereInput={tenantId,status:query.status as SalesDocumentStatus,OR:query.search?[{documentNumber:{contains:query.search,mode:"insensitive"}},{customer:{displayName:{contains:query.search,mode:"insensitive"}}}]:undefined}; const [items,total]=await this.prisma.$transaction([this.prisma.quote.findMany({where,include:{customer:true,items:{include:{product:true}}},skip:(page-1)*limit,take:limit,orderBy:{createdAt:"desc"}}),this.prisma.quote.count({where})]); return {items:withDocumentNumbers(items),meta:{page,limit,total,pageCount:Math.ceil(total/limit)}}; }
  async findOne(tenantId: string, id: string) { const quote=await this.prisma.quote.findFirst({where:{id,tenantId},include:{customer:true,items:{include:{product:true}},proformas:true}}); if(!quote) throw new NotFoundException("Devis introuvable"); return withDocumentNumber({ ...quote, customerHistoryPrepared: true, printFormats: ["POS_58_80", "A4_LETTER"] }); }
  async create(tenantId: string, dto: CreateSalesDocumentDto, createdById?: string) { await ensureCustomer(this.prisma,tenantId,dto.customerId); await ensureProducts(this.prisma,tenantId,dto.items.map(i=>i.productId)); const totals=calculateDocumentTotals(dto.items,dto.discount??0); const quote=await this.prisma.quote.create({data:{tenantId,customerId:dto.customerId,documentNumber:generateDocumentNumber("QT"),notes:dto.notes,createdById,...totals,items:{create:mapDocumentItems(dto.items)}},include:{customer:true,items:{include:{product:true}}}}); return withDocumentNumber(quote); }
  async update(tenantId: string, id: string, dto: UpdateSalesDocumentDto) { const quote=await this.findOne(tenantId,id); if (!([SalesDocumentStatus.DRAFT,SalesDocumentStatus.SENT] as SalesDocumentStatus[]).includes(quote.status)) throw new BadRequestException("Ce devis ne peut plus etre modifie"); await ensureCustomer(this.prisma,tenantId,dto.customerId); await ensureProducts(this.prisma,tenantId,dto.items.map(i=>i.productId)); const totals=calculateDocumentTotals(dto.items,dto.discount??0); const updated=await this.prisma.quote.update({where:{id},data:{customerId:dto.customerId,notes:dto.notes,...totals,items:{deleteMany:{},create:mapDocumentItems(dto.items)}},include:{customer:true,items:{include:{product:true}}}}); return withDocumentNumber(updated); }
  async send(tenantId: string, id: string) { await this.findOne(tenantId,id); return withDocumentNumber(await this.prisma.quote.update({where:{id},data:{status:SalesDocumentStatus.SENT,sentAt:new Date()}})); }
  async accept(tenantId: string, id: string) { await this.findOne(tenantId,id); return withDocumentNumber(await this.prisma.quote.update({where:{id},data:{status:SalesDocumentStatus.ACCEPTED,acceptedAt:new Date()}})); }
  async reject(tenantId: string, id: string) { await this.findOne(tenantId,id); return withDocumentNumber(await this.prisma.quote.update({where:{id},data:{status:SalesDocumentStatus.REJECTED,rejectedAt:new Date()}})); }
  async convertToProforma(tenantId: string, id: string, createdById?: string) { const quote=await this.findOne(tenantId,id); if(([SalesDocumentStatus.REJECTED,SalesDocumentStatus.CANCELLED] as SalesDocumentStatus[]).includes(quote.status)) throw new BadRequestException("Ce devis ne peut pas etre transforme"); const proforma=await this.prisma.proforma.create({data:{tenantId,customerId:quote.customerId,quoteId:quote.id,documentNumber:generateDocumentNumber("PF"),status:SalesDocumentStatus.DRAFT,subtotal:quote.subtotal,discount:quote.discount,tax:quote.tax,total:quote.total,paidAmount:0,balance:quote.balance,notes:quote.notes,createdById,items:{create:quote.items.map((item:any)=>({productId:item.productId,quantity:item.quantity,unitPrice:item.unitPrice,discount:item.discount,tax:item.tax,total:item.total}))}},include:{customer:true,items:{include:{product:true}}}}); await this.prisma.quote.update({where:{id},data:{status:SalesDocumentStatus.CONVERTED}}); return withDocumentNumber(proforma); }
}