ALTER TABLE "SaleItem" ALTER COLUMN "productId" DROP NOT NULL;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "customName" TEXT;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "customType" TEXT;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "customNote" TEXT;

ALTER TABLE "QuoteItem" ALTER COLUMN "productId" DROP NOT NULL;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "customName" TEXT;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "customType" TEXT;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "customNote" TEXT;

ALTER TABLE "ProformaItem" ALTER COLUMN "productId" DROP NOT NULL;
ALTER TABLE "ProformaItem" ADD COLUMN IF NOT EXISTS "customName" TEXT;
ALTER TABLE "ProformaItem" ADD COLUMN IF NOT EXISTS "customType" TEXT;
ALTER TABLE "ProformaItem" ADD COLUMN IF NOT EXISTS "customNote" TEXT;

ALTER TABLE "InvoiceItem" ALTER COLUMN "productId" DROP NOT NULL;
ALTER TABLE "InvoiceItem" ADD COLUMN IF NOT EXISTS "customName" TEXT;
ALTER TABLE "InvoiceItem" ADD COLUMN IF NOT EXISTS "customType" TEXT;
ALTER TABLE "InvoiceItem" ADD COLUMN IF NOT EXISTS "customNote" TEXT;
