"use client";
import { apiBaseUrl as apiUrl } from "@/lib/api-url";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { getAccessToken } from "@/lib/auth";
type Permission = { id: string; key: string; name: string; category: string };
type Role = { id: string; name: string; description?: string; permissions?: { permission: Permission }[] };
export default function RolesSettingsPage() {
  const [roles,setRoles]=useState<Role[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [selectedPermissionIds,setSelectedPermissionIds]=useState<string[]>([]); const [selectedRole,setSelectedRole]=useState<Role|null>(null); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{loadData();},[]);
  async function loadData(){ const token=getAccessToken(); const headers={Authorization:`Bearer ${token}`}; const [r,p]=await Promise.all([fetch(`${apiUrl}/roles`,{headers}),fetch(`${apiUrl}/permissions`,{headers})]); if(r.ok)setRoles(await r.json()); if(p.ok)setPermissions(await p.json()); }
  async function handleSubmit(event:FormEvent<HTMLFormElement>){ event.preventDefault(); const token=getAccessToken(); const response=await fetch(selectedRole?`${apiUrl}/roles/${selectedRole.id}`:`${apiUrl}/roles`,{method:selectedRole?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({name,description,permissionIds:selectedPermissionIds})}); setMessage(response.ok?"Rôle enregistré avec succès.":"Impossible d'enregistrer le rôle."); if(response.ok){setName("");setDescription("");setSelectedPermissionIds([]);setSelectedRole(null);await loadData();}}
  function editRole(role:Role){setSelectedRole(role);setName(role.name);setDescription(role.description??"");setSelectedPermissionIds(role.permissions?.map((item)=>item.permission.id)??[]);}
  const grouped=useMemo(()=>permissions.reduce<Record<string,Permission[]>>((groups,permission)=>{groups[permission.category]=[...(groups[permission.category]??[]),permission];return groups;},{}),[permissions]);
  return <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm font-medium text-brand-600">Paramètres</p><h1 className="mt-2 text-2xl font-bold text-slate-950 dark:text-white">Rôles</h1><form className="mt-5 space-y-4" onSubmit={handleSubmit}><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Nom du rôle" className="w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-950"/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Description" className="min-h-24 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-950"/><button className="w-full rounded-md bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700">{selectedRole?"Modifier":"Créer"}</button>{message?<p className="text-sm text-slate-600 dark:text-slate-300">{message}</p>:null}</form></section><section className="space-y-4"><div className="grid gap-3 md:grid-cols-2">{roles.map((role)=><button key={role.id} onClick={()=>editRole(role)} className="rounded-lg border border-slate-200 bg-white p-4 text-left shadow-sm hover:border-brand-600 dark:border-slate-800 dark:bg-slate-900"><p className="font-semibold text-slate-950 dark:text-white">{role.name}</p><p className="mt-1 text-sm text-slate-500">{role.description??"Aucune description"}</p><p className="mt-3 text-xs text-brand-600">{role.permissions?.length??0} permissions</p></button>)}</div><div className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold text-slate-950 dark:text-white">Attribuer les permissions</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{Object.entries(grouped).map(([category,items])=><div key={category}><p className="mb-2 text-sm font-semibold text-slate-700 dark:text-slate-200">{category}</p><div className="space-y-2">{items.map((permission)=><label key={permission.id} className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-300"><input type="checkbox" checked={selectedPermissionIds.includes(permission.id)} onChange={(e)=>setSelectedPermissionIds((current)=>e.target.checked?[...current,permission.id]:current.filter((id)=>id!==permission.id))}/>{permission.name}</label>)}</div></div>)}</div></div></section></div>;
}
