export const defaultPermissions = [
  { key: "dashboard.view", name: "Dashboard.view", category: "Dashboard", description: "Permission Dashboard.view" },
  { key: "dashboard.export", name: "Dashboard.export", category: "Dashboard", description: "Permission Dashboard.export" },
  { key: "dashboard.widgets.manage", name: "Dashboard.widgets.manage", category: "Dashboard", description: "Permission Dashboard.widgets.manage" },
  { key: "dashboard.metrics.view", name: "Dashboard.metrics.view", category: "Dashboard", description: "Permission Dashboard.metrics.view" },
  { key: "dashboard.revenue.view", name: "Dashboard.revenue.view", category: "Dashboard", description: "Permission Dashboard.revenue.view" },
  { key: "dashboard.alerts.view", name: "Dashboard.alerts.view", category: "Dashboard", description: "Permission Dashboard.alerts.view" },
  { key: "users.view", name: "Users.view", category: "Users", description: "Permission Users.view" },
  { key: "users.create", name: "Users.create", category: "Users", description: "Permission Users.create" },
  { key: "users.update", name: "Users.update", category: "Users", description: "Permission Users.update" },
  { key: "users.delete", name: "Users.delete", category: "Users", description: "Permission Users.delete" },
  { key: "users.invite", name: "Users.invite", category: "Users", description: "Permission Users.invite" },
  { key: "users.reset_password", name: "Users.reset_password", category: "Users", description: "Permission Users.reset_password" },
  { key: "roles.view", name: "Roles.view", category: "Roles", description: "Permission Roles.view" },
  { key: "roles.create", name: "Roles.create", category: "Roles", description: "Permission Roles.create" },
  { key: "roles.update", name: "Roles.update", category: "Roles", description: "Permission Roles.update" },
  { key: "roles.delete", name: "Roles.delete", category: "Roles", description: "Permission Roles.delete" },
  { key: "roles.assign", name: "Roles.assign", category: "Roles", description: "Permission Roles.assign" },
  { key: "roles.audit", name: "Roles.audit", category: "Roles", description: "Permission Roles.audit" },
  { key: "permissions.view", name: "Permissions.view", category: "Permissions", description: "Permission Permissions.view" },
  { key: "permissions.create", name: "Permissions.create", category: "Permissions", description: "Permission Permissions.create" },
  { key: "permissions.update", name: "Permissions.update", category: "Permissions", description: "Permission Permissions.update" },
  { key: "permissions.delete", name: "Permissions.delete", category: "Permissions", description: "Permission Permissions.delete" },
  { key: "permissions.assign", name: "Permissions.assign", category: "Permissions", description: "Permission Permissions.assign" },
  { key: "permissions.audit", name: "Permissions.audit", category: "Permissions", description: "Permission Permissions.audit" },
  { key: "tenants.view", name: "Tenants.view", category: "Tenants", description: "Permission Tenants.view" },
  { key: "tenants.create", name: "Tenants.create", category: "Tenants", description: "Permission Tenants.create" },
  { key: "tenants.update", name: "Tenants.update", category: "Tenants", description: "Permission Tenants.update" },
  { key: "tenants.delete", name: "Tenants.delete", category: "Tenants", description: "Permission Tenants.delete" },
  { key: "tenants.settings.manage", name: "Tenants.settings.manage", category: "Tenants", description: "Permission Tenants.settings.manage" },
  { key: "tenants.subscription.manage", name: "Tenants.subscription.manage", category: "Tenants", description: "Permission Tenants.subscription.manage" },
  { key: "products.view", name: "Products.view", category: "Products", description: "Permission Products.view" },
  { key: "products.create", name: "Products.create", category: "Products", description: "Permission Products.create" },
  { key: "products.update", name: "Products.update", category: "Products", description: "Permission Products.update" },
  { key: "products.delete", name: "Products.delete", category: "Products", description: "Permission Products.delete" },
  { key: "products.import", name: "Products.import", category: "Products", description: "Permission Products.import" },
  { key: "products.export", name: "Products.export", category: "Products", description: "Permission Products.export" },
  { key: "inventory.view", name: "Inventory.view", category: "Inventory", description: "Permission Inventory.view" },
  { key: "inventory.adjust", name: "Inventory.adjust", category: "Inventory", description: "Permission Inventory.adjust" },
  { key: "inventory.transfer", name: "Inventory.transfer", category: "Inventory", description: "Permission Inventory.transfer" },
  { key: "inventory.count", name: "Inventory.count", category: "Inventory", description: "Permission Inventory.count" },
  { key: "inventory.low_stock.view", name: "Inventory.low_stock.view", category: "Inventory", description: "Permission Inventory.low_stock.view" },
  { key: "inventory.audit", name: "Inventory.audit", category: "Inventory", description: "Permission Inventory.audit" },
  { key: "sales.read", name: "Sales.read", category: "Sales", description: "Lire les ventes" },
  { key: "sales.create", name: "Sales.create", category: "Sales", description: "Creer des ventes" },
  { key: "sales.update", name: "Sales.update", category: "Sales", description: "Modifier les ventes" },
  { key: "sales.delete", name: "Sales.delete", category: "Sales", description: "Supprimer les ventes" },
  { key: "quote.read", name: "Quote.read", category: "Sales", description: "Lire les devis" },
  { key: "quote.create", name: "Quote.create", category: "Sales", description: "Creer les devis" },
  { key: "quote.update", name: "Quote.update", category: "Sales", description: "Modifier les devis" },
  { key: "quote.convert", name: "Quote.convert", category: "Sales", description: "Transformer les devis" },
  { key: "proforma.read", name: "Proforma.read", category: "Sales", description: "Lire les proformas" },
  { key: "proforma.create", name: "Proforma.create", category: "Sales", description: "Creer les proformas" },
  { key: "proforma.update", name: "Proforma.update", category: "Sales", description: "Modifier les proformas" },
  { key: "proforma.convert", name: "Proforma.convert", category: "Sales", description: "Transformer les proformas" },
  { key: "invoice.read", name: "Invoice.read", category: "Sales", description: "Lire les factures" },
  { key: "invoice.create", name: "Invoice.create", category: "Sales", description: "Creer les factures" },
  { key: "invoice.update", name: "Invoice.update", category: "Sales", description: "Modifier les factures" },
  { key: "invoice.cancel", name: "Invoice.cancel", category: "Sales", description: "Annuler les factures" },
  { key: "invoice.print", name: "Invoice.print", category: "Sales", description: "Imprimer les factures" },
  { key: "payment.read", name: "Payment.read", category: "Sales", description: "Lire les paiements" },
  { key: "payment.create", name: "Payment.create", category: "Sales", description: "Enregistrer les paiements" },
  { key: "return.read", name: "Return.read", category: "Sales", description: "Lire les retours" },
  { key: "return.create", name: "Return.create", category: "Sales", description: "Creer les retours" },
  { key: "sales.view", name: "Sales.view", category: "Sales", description: "Permission Sales.view" },
  { key: "sales.cancel", name: "Sales.cancel", category: "Sales", description: "Permission Sales.cancel" },
  { key: "sales.refund", name: "Sales.refund", category: "Sales", description: "Permission Sales.refund" },
  { key: "sales.export", name: "Sales.export", category: "Sales", description: "Permission Sales.export" },
  { key: "cash.read", name: "Cash.read", category: "Cash", description: "Lire les caisses" },
  { key: "cash.create", name: "Cash.create", category: "Cash", description: "Creer des caisses" },
  { key: "cash.open", name: "Cash.open", category: "Cash", description: "Ouvrir une caisse" },
  { key: "cash.close", name: "Cash.close", category: "Cash", description: "Fermer une caisse" },
  { key: "cash.movement", name: "Cash.movement", category: "Cash", description: "Enregistrer les mouvements de caisse" },
  { key: "cash.report", name: "Cash.report", category: "Cash", description: "Voir les rapports de caisse" },  { key: "pos.open", name: "POS.open", category: "POS", description: "Permission POS.open" },
  { key: "pos.close", name: "POS.close", category: "POS", description: "Permission POS.close" },
  { key: "pos.sell", name: "POS.sell", category: "POS", description: "Permission POS.sell" },
  { key: "pos.discount", name: "POS.discount", category: "POS", description: "Permission POS.discount" },
  { key: "pos.refund", name: "POS.refund", category: "POS", description: "Permission POS.refund" },
  { key: "pos.cash_drawer.manage", name: "POS.cash_drawer.manage", category: "POS", description: "Permission POS.cash_drawer.manage" },
  { key: "customer.read", name: "Customer.read", category: "Customers", description: "Lire les clients CRM" },
  { key: "customer.create", name: "Customer.create", category: "Customers", description: "Creer des clients CRM" },
  { key: "customer.update", name: "Customer.update", category: "Customers", description: "Modifier les clients CRM" },
  { key: "customer.delete", name: "Customer.delete", category: "Customers", description: "Archiver ou supprimer les clients CRM" },
  { key: "customer.export", name: "Customer.export", category: "Customers", description: "Exporter les clients CRM" },
  { key: "customer.import", name: "Customer.import", category: "Customers", description: "Importer les clients CRM" },
  { key: "customers.view", name: "Customers.view", category: "Customers", description: "Permission Customers.view" },
  { key: "customers.create", name: "Customers.create", category: "Customers", description: "Permission Customers.create" },
  { key: "customers.update", name: "Customers.update", category: "Customers", description: "Permission Customers.update" },
  { key: "customers.delete", name: "Customers.delete", category: "Customers", description: "Permission Customers.delete" },
  { key: "customers.credit.manage", name: "Customers.credit.manage", category: "Customers", description: "Permission Customers.credit.manage" },
  { key: "customers.export", name: "Customers.export", category: "Customers", description: "Permission Customers.export" },
  { key: "suppliers.view", name: "Suppliers.view", category: "Suppliers", description: "Permission Suppliers.view" },
  { key: "suppliers.create", name: "Suppliers.create", category: "Suppliers", description: "Permission Suppliers.create" },
  { key: "suppliers.update", name: "Suppliers.update", category: "Suppliers", description: "Permission Suppliers.update" },
  { key: "suppliers.delete", name: "Suppliers.delete", category: "Suppliers", description: "Permission Suppliers.delete" },
  { key: "suppliers.orders.view", name: "Suppliers.orders.view", category: "Suppliers", description: "Permission Suppliers.orders.view" },
  { key: "suppliers.export", name: "Suppliers.export", category: "Suppliers", description: "Permission Suppliers.export" },
  { key: "purchases.view", name: "Purchases.view", category: "Purchases", description: "Permission Purchases.view" },
  { key: "purchases.create", name: "Purchases.create", category: "Purchases", description: "Permission Purchases.create" },
  { key: "purchases.update", name: "Purchases.update", category: "Purchases", description: "Permission Purchases.update" },
  { key: "purchases.approve", name: "Purchases.approve", category: "Purchases", description: "Permission Purchases.approve" },
  { key: "purchases.cancel", name: "Purchases.cancel", category: "Purchases", description: "Permission Purchases.cancel" },
  { key: "purchases.receive", name: "Purchases.receive", category: "Purchases", description: "Permission Purchases.receive" },
  { key: "purchases.export", name: "Purchases.export", category: "Purchases", description: "Exporter les achats" },
  { key: "invoices.view", name: "Invoices.view", category: "Invoices", description: "Permission Invoices.view" },
  { key: "invoices.create", name: "Invoices.create", category: "Invoices", description: "Permission Invoices.create" },
  { key: "invoices.update", name: "Invoices.update", category: "Invoices", description: "Permission Invoices.update" },
  { key: "invoices.delete", name: "Invoices.delete", category: "Invoices", description: "Permission Invoices.delete" },
  { key: "invoices.send", name: "Invoices.send", category: "Invoices", description: "Permission Invoices.send" },
  { key: "invoices.payments.manage", name: "Invoices.payments.manage", category: "Invoices", description: "Permission Invoices.payments.manage" },
  { key: "reports.view", name: "Reports.view", category: "Reports", description: "Permission Reports.view" },
  { key: "reports.read", name: "Reports.read", category: "Reports", description: "Lire les rapports" },
  { key: "reports.products", name: "Reports.products", category: "Reports", description: "Lire le rapport produits" },
  { key: "reports.customers", name: "Reports.customers", category: "Reports", description: "Lire le rapport clients" },
  { key: "reports.purchases", name: "Reports.purchases", category: "Reports", description: "Lire le rapport achats" },
  { key: "reports.profit", name: "Reports.profit", category: "Reports", description: "Lire le rapport profits" },
  { key: "reports.sales", name: "Reports.sales", category: "Reports", description: "Permission Reports.sales" },
  { key: "reports.inventory", name: "Reports.inventory", category: "Reports", description: "Permission Reports.inventory" },
  { key: "reports.accounting", name: "Reports.accounting", category: "Reports", description: "Permission Reports.accounting" },
  { key: "reports.export", name: "Reports.export", category: "Reports", description: "Permission Reports.export" },
  { key: "reports.schedule", name: "Reports.schedule", category: "Reports", description: "Permission Reports.schedule" },
  { key: "accounting.view", name: "Accounting.view", category: "Accounting", description: "Permission Accounting.view" },
  { key: "accounting.entries.create", name: "Accounting.entries.create", category: "Accounting", description: "Permission Accounting.entries.create" },
  { key: "accounting.entries.update", name: "Accounting.entries.update", category: "Accounting", description: "Permission Accounting.entries.update" },
  { key: "accounting.reconcile", name: "Accounting.reconcile", category: "Accounting", description: "Permission Accounting.reconcile" },
  { key: "accounting.taxes.manage", name: "Accounting.taxes.manage", category: "Accounting", description: "Permission Accounting.taxes.manage" },
  { key: "accounting.export", name: "Accounting.export", category: "Accounting", description: "Permission Accounting.export" },
  { key: "import.read", name: "Import.read", category: "Import", description: "Lire les imports" },
  { key: "import.products", name: "Import.products", category: "Import", description: "Importer les produits" },
  { key: "import.customers", name: "Import.customers", category: "Import", description: "Importer les clients" },
  { key: "import.suppliers", name: "Import.suppliers", category: "Import", description: "Importer les fournisseurs" },
  { key: "export.read", name: "Export.read", category: "Export", description: "Lire les exports" },
  { key: "export.products", name: "Export.products", category: "Export", description: "Exporter les produits" },
  { key: "export.customers", name: "Export.customers", category: "Export", description: "Exporter les clients" },
  { key: "export.suppliers", name: "Export.suppliers", category: "Export", description: "Exporter les fournisseurs" },
  { key: "export.inventory", name: "Export.inventory", category: "Export", description: "Exporter l'inventaire" },  { key: "backup.read", name: "Backup.read", category: "Backup", description: "Lire les sauvegardes" },
  { key: "backup.create", name: "Backup.create", category: "Backup", description: "Creer une sauvegarde" },
  { key: "security.read", name: "Security.read", category: "Security", description: "Lire les journaux de securite" },
  { key: "audit.read", name: "Audit.read", category: "Audit", description: "Lire les journaux d'audit" },
  { key: "audit.export", name: "Audit.export", category: "Audit", description: "Exporter les journaux d'audit" },  { key: "store.read", name: "Store.read", category: "Stores", description: "Lire les magasins" },
  { key: "store.create", name: "Store.create", category: "Stores", description: "Creer les magasins" },
  { key: "store.update", name: "Store.update", category: "Stores", description: "Modifier les magasins" },
  { key: "store.delete", name: "Store.delete", category: "Stores", description: "Fermer les magasins" },
  { key: "warehouse.read", name: "Warehouse.read", category: "Warehouses", description: "Lire les depots" },
  { key: "warehouse.create", name: "Warehouse.create", category: "Warehouses", description: "Creer les depots" },
  { key: "warehouse.update", name: "Warehouse.update", category: "Warehouses", description: "Modifier les depots" },
  { key: "warehouse.delete", name: "Warehouse.delete", category: "Warehouses", description: "Supprimer les depots" },
  { key: "transfer.read", name: "Transfer.read", category: "Transfers", description: "Lire les transferts" },
  { key: "transfer.create", name: "Transfer.create", category: "Transfers", description: "Creer les transferts" },
  { key: "transfer.validate", name: "Transfer.validate", category: "Transfers", description: "Valider les transferts" },  { key: "notifications.read", name: "Notifications.read", category: "Notifications", description: "Lire les notifications" },
  { key: "notifications.update", name: "Notifications.update", category: "Notifications", description: "Mettre a jour les notifications" },
  { key: "notifications.archive", name: "Notifications.archive", category: "Notifications", description: "Archiver les notifications" },  { key: "settings.read", name: "Settings.read", category: "Settings", description: "Lire les parametres" },
  { key: "settings.company", name: "Settings.company", category: "Settings", description: "Gerer le profil entreprise" },
  { key: "settings.pos", name: "Settings.pos", category: "Settings", description: "Gerer les parametres POS" },
  { key: "settings.invoicing", name: "Settings.invoicing", category: "Settings", description: "Gerer les parametres de facturation" },  { key: "settings.view", name: "Settings.view", category: "Settings", description: "Permission Settings.view" },
  { key: "settings.update", name: "Settings.update", category: "Settings", description: "Permission Settings.update" },
  { key: "settings.security.manage", name: "Settings.security.manage", category: "Settings", description: "Permission Settings.security.manage" },
  { key: "settings.billing.manage", name: "Settings.billing.manage", category: "Settings", description: "Permission Settings.billing.manage" },
  { key: "settings.integrations.manage", name: "Settings.integrations.manage", category: "Settings", description: "Permission Settings.integrations.manage" },
  { key: "settings.audit.view", name: "Settings.audit.view", category: "Settings", description: "Permission Settings.audit.view" }
  ,{ key: "business.read", name: "Business.read", category: "Business", description: "Lire les profils et modules metier" }
  ,{ key: "business.update", name: "Business.update", category: "Business", description: "Activer ou desactiver les profils metier" }
] as const;
